services:
  - type: worker
    name: telegram-gemini-bot
    env: python
    pythonVersion: 3.11.9
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
